currencies = {
  'EUR' : 'Euro',
  'USD' : 'US dollar',
  'GBP' : 'Pound sterling',
  'AED' : 'Arab Emirates dirham',
  'AUD' : 'Australian dollar',
  'BGN' : 'Bulgarian lev',
  'BRL' : 'Brasilian real',
  'CAD' : 'Canadian dollar',
  'CHF' : 'Swiss franc',
  'CNY' : 'Chinese yuan renminbi',
  'CZK' : 'Czech koruna',
  'DKK' : 'Danish krone',
  'EEK' : 'Estonian kroon',
  'EGP' : 'Egyptian Pound',
  'FJD' : 'Fijian Dollar',
  'GEL' : 'Georgian Lari',
  'HKD' : 'Hong Kong dollar',
  'HRK' : 'Croatian kuna',
  'HUF' : 'Hungarian forint',
  'IDR' : 'Indonesian rupiah',
  'INR' : 'Indian rupee',
  'ILS' : 'Israeli shekel',
  'JPY' : 'Japanese yen',
  'KRW' : 'South Korean won',
  'KES' : 'Kenyan shilling',
  'KWD' : 'Kuwaiti dinar',
  'LKR' : 'Sri Lankan Rupee',
  'LTL' : 'Lithuanian litas',
  'LVL' : 'Latvian lats',
  'MXN' : 'Mexican peso',
  'MYR' : 'Malaysian ringgit',
  'NOK' : 'Norwegian krone',
  'NZD' : 'New Zealand dollar',
  'PHP' : 'Philippine peso',
  'PKR' : 'Pakistan Rupee',
  'PLN' : 'Polish zloty',
  'RON' : 'New Romanian',
  'RUB' : 'Russian rouble',
  'SAR' : 'Saudi Riyal',
  'SEK' : 'Swedish krona',
  'SGD' : 'Singapore dollar',
  'THB' : 'Thai baht',
  'TRY' : 'Turkish lira',
  'TTD' : 'Trinidad dollar',
  'UAH' : 'Ukrainian grivna',
  'ZAR' : 'South African rand'
};